{{- define "common.istio_base" -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: product-composite-require-jwt
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      app.kubernetes.io/name: product-composite
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  #namespace: istio-system
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gutenberg-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - minikube.gutenberg
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: gutenberg-certificate
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gutenberg-vs
spec:
  gateways:
  - gutenberg-gw
  hosts:
  - minikube.gutenberg
  http: 
  - match:
    - uri:
        prefix: "/book/"
    - uri:
        exact: "/book"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: book.gutenberg.svc.cluster.local
        port:
          number: 80 
  - match:
    - uri:
        prefix: "/review/"
    - uri:
        exact: "/review"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: review.gutenberg.svc.cluster.local
        port:
          number: 80                      
  - match:
    - uri:
        prefix: "/order/"
    - uri:
        exact: "/order"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: order.gutenberg.svc.cluster.local
        port:
          number: 80  
  - match:
    - uri:
        prefix: "/user/"
    - uri:
        exact: "/user"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: user.gutenberg.svc.cluster.local
        port:
          number: 80  
  - match:
    - uri:
        prefix: "/composite/"
    - uri:
        exact: "/composite"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: composite.gutenberg.svc.cluster.local
        port:
          number: 80    
  - match:
    - uri:
        prefix: "/singe/"
    - uri:
        exact: "/singe"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: singe.gutenberg.svc.cluster.local
        port:
          number: 80                                                   
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: health-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "health.minikube.gutenberg"
    port:
      number: 443
      name: https-health
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: gutenberg-certificate
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: health-vs
spec:
  hosts:
  - "health.minikube.gutenberg"
  gateways:
  - health-gateway
  http:
  - match:
    - uri:
        prefix: "/book/"
    - uri:
        exact: "/book"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: book.gutenberg.svc.cluster.local
        port:
          number: 4004
  - match:
    - uri:
        prefix: "/review/"
    - uri:
        exact: "/review"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: review.gutenberg.svc.cluster.local
        port:
          number: 4004        
  - match:
    - uri:
        prefix: "/order/"
    - uri:
        exact: "/order"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: order.gutenberg.svc.cluster.local
        port:
          number: 4004 
  - match:
    - uri:
        prefix: "/user/"
    - uri:
        exact: "/user"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: user.gutenberg.svc.cluster.local
        port:
          number: 4004                                  
  - match:
    - uri:
        prefix: "/composite/"
    - uri:
        exact: "/composite"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: composite.gutenberg.svc.cluster.local
        port:
          number: 4004
  - match:
    - uri:
        prefix: "/singe/"
    - uri:
        exact: "/singe"    
    rewrite:
      uri: "/"
    route:
    - destination:
        host: singe.gutenberg.svc.cluster.local
        port:
          number: 4004                            
          
                  
  #- route:
  #  - destination:
  #      host: product-composite
  #      port:
  #        number: 4004
{{- end -}}
