secrets:

  rabbitmq-server-credentials:
    RABBITMQ_DEFAULT_USER: rabbit-user-dev
    RABBITMQ_DEFAULT_PASS: rabbit-pwd-dev

  rabbitmq-credentials:
    SPRING_RABBITMQ_USERNAME: rabbit-user-dev
    SPRING_RABBITMQ_PASSWORD: rabbit-pwd-dev

  mongodb-server-credentials:
    MONGO_INITDB_ROOT_USERNAME: mongodb-user-dev
    MONGO_INITDB_ROOT_PASSWORD: mongodb-pwd-dev

  mongodb-credentials:
    SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    SPRING_DATA_MONGODB_USERNAME: mongodb-user-dev
    SPRING_DATA_MONGODB_PASSWORD: mongodb-pwd-dev


rabbitmq:
  envFromSecretRefs:
    - rabbitmq-server-credentials

mongodb:
  envFromSecretRefs:
    - mongodb-server-credentials

user:
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials

    
order:
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials 


composite:
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials  
    
book:
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials    

review:
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials 

destinationRules:
  - name: book
  - name: review
  - name: order
  - name: user
  #- name: singe 
  
